---
name: PR Checks
run-name: >
  Verify build and test - '${{ github.event.pull_request.title }}',
  from ${{ github.ref }} by @${{ github.actor }}

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 10.0.x
  DEBUG: true

jobs:
  debug:
    name: Debug Info
    runs-on: ubuntu-latest
    if: vars.DEBUG == 'true'
    steps:
      - name: Print GitHub object
        run: |
          echo "${{ toJSON(github) }}" > debug.txt
      - name: Upload debug info
        uses: actions/upload-artifact@v6
        with:
          name: debug-info
          path: debug.txt


  # Determining next release version from current release version
  determine-next-release-version:
    name: Determine next Release version
    uses: ./.github/workflows/determine-next-release-version.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  version-pr-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: determine-next-release-version
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: >
            Merging this PR will increase the release version from
            **${{ needs.determine-next-release-version.outputs.current_version }}**
            to **${{ needs.determine-next-release-version.outputs.version }}**.

  # CI: build and verify tests
  build-and-verify:
    name: Build source code and verify tests
    needs: determine-next-release-version
    uses: ./.github/workflows/dotnet-build-and-verify.yaml
    with:
      configuration: Release  # ${{ env.CONFIGURATION }}
      dotnet-versions: 10.0.x  # ${{ env.DOTNET_CORE_VERSION }}
      version: ${{ needs.determine-next-release-version.outputs.version }}
      source-directory: ./src
      artifact-name: Packages
      main-library-subdir: DotnetPsCmds
